### ISSUE TITLE
 WebapiRegularError: An error occurred while communicating with Spotify's Web API.

### ISSUE THREAD

**Issue by Sordinni** [AlenVelocity/spotifydl-core#6]
Details: non existing id.
    at _toError (C:\Users\sordi\urepirso\node_modules\spotify-web-api-node\src\http-manager.js:39:12)
    at C:\Users\sordi\urepirso\node_modules\spotify-web-api-node\src\http-manager.js:71:25
    at Request.callback (C:\Users\sordi\urepirso\node_modules\superagent\lib\node\index.js:905:3)
    at C:\Users\sordi\urepirso\node_modules\superagent\lib\node\index.js:1127:20
    at IncomingMessage.<anonymous> (C:\Users\sordi\urepirso\node_modules\superagent\lib\node\parsers\json.js:22:7)
    at Stream.emit (node:events:513:28)
    at Unzip.<anonymous> (C:\Users\sordi\urepirso\node_modules\superagent\lib\node\unzip.js:53:12)
    at Unzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  body: { error: { status: 404, message: 'non existing id' } },
  headers: {
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'private, max-age=0',
    'x-robots-tag': 'noindex, nofollow',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token',
    'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
    'access-control-allow-credentials': 'true',
    'access-control-max-age': '604800',
    'content-encoding': 'gzip',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    date: 'Sun, 25 Sep 2022 04:00:44 GMT',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 404
}

**Comment by domdewom** [comment]
Curious, did you use a Song or Podcast Episode when you got above error message?
